### ISSUE TITLE
[Feature] - Miranum Modeler supports Camunda 8 properties

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#104]
- [x] Description created 
- [x] Reviewed by peer (24 hr window): @peterhnm 
- [x] Prioritised

# Description 
We want the vs-code plugin of the Miranum Modeler to support Camunda Platform 8 properties, so people can model their diagrams in there. This can be an entry point for users and a further reason to discover Miranum. 

## Sub-Tasks 
```[tasklist]
### Tasks
- [x] Support Camunda 8 properties in Miranum Modeler
- [x] Update Documentation
- [x] Release the new functionality
```

**Comment by peterhnm** [comment]
What should it look like. Like in "Camunda Modeler", that the user is asked at the beginning for which version to model?

**Comment by Hafflgav** [comment]
That's a good question. 🤔 
I would say we create by default a Camunda 7 model without asking. But when opening an existing model for Camunda 8, we can show the actual properties panel. 

That seems to me is less work intensive. When we get some more feedback about it we can add such a "landing page" as in the Camunda Modeler later on. 

Wdyt?

**Comment by peterhnm** [comment]
> But when opening an existing model for Camunda 8, we can show the actual properties panel.

Does this mean that the properties panel is a different one to a Camunda 7 model?

**Comment by Hafflgav** [comment]
Yes @peterhnm! :) 
Taking a look into the Camunda Modeler it differs from each other. 
E.g. for a service task: 

Camunda 7: 
![image](https://user-images.githubusercontent.com/30292227/223082455-56962509-2410-4b45-a69f-797706b1e67c.png)

Camunda 8: 
![image](https://user-images.githubusercontent.com/30292227/223082533-453ccb22-3c32-4008-a908-da3a2fde7c62.png)

**Comment by peterhnm** [comment]
Allright. Does this also have an effect on how to customize the panel? For example we extend panel with the [element-tamplates-chooser](https://github.com/bpmn-io/element-template-chooser) and a [custom property](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension).

**Comment by Hafflgav** [comment]
Good question... 🤔 
For now I would add neither of them to a C8 compatible model. Basically just the plain properties panel without any extensions. Just to provide the possibility to work with C8 models in VS-Code.

**Comment by peterhnm** [comment]
Helpful links:
* [camunda-bpmn-js](https://www.npmjs.com/package/camunda-bpmn-js)
* [Properties Panel Example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel)
