### ISSUE TITLE
[Feature] - Add PDF templating for Miranum IDE

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#105]
- [ ] Description created 
- [ ] Reviewed by peer (24 hr window): <tag-person-here>
- [ ] Prioritised

# Description 
With Miranum IDE we want to be able to provide a task management and forms handling platform. Documents are usually essential to these kind of use cases. Hence we want to be able to support them. 
To do so we want to be able to work and with and generate PDF templates.

## Sub-Tasks 

```[tasklist]
### Tasks
- [ ] Research on whether we can build PDF Templates on top of our form builder
- [ ] Create a prototype 
- [ ] Update Documentation
- [ ] Release vs-code plugin 
```
