### ISSUE TITLE
[Feature] CLI: Generate Integration Starter Project

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#117]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
As a user I want to use the miranum-cli to also create a starter project for my integration featuring miranum-connect. This allows me to get started quicker and have one place to kick-off my whole process application.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Think about and define the expected stater project for an integration 
- [ ] Add the creation of it to the miranum-cli
- [ ] Test it and ...
- [ ] add it to the documentation
```
