### ISSUE TITLE
[Epic] Custom Eclipse Theia IDE

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#120]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
On the base of eclipse theia we want to release a custom miranum ide that comes with our VS-Code Plugins preinstalled.

> Eclipse Theia is a project of the eclipse foundation that uses vs-code to create (web) ides

The main purpose of this is to provide a easy way to use our ide for less technical users (e.g. Standalone application).

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Create custom eclipse theia ide
- [ ] Use our extension bundle
- [ ] Customize UI of eclipse theia ide
- [ ] Release the eclipse theia ide application
- [ ] Create documentation
```

## Stakeholder
@dominikhorn93 

# Acceptance

- [ ] Miranum-IDE can be downloaded and installed as standalone application

**Comment by Hafflgav** [comment]
Hey @lmoesle - I assigned you to this epic since I assume you have the most knowledge in this area. Could you be the driver for this one and create issues for the tasks if they are applicable?
