### ISSUE TITLE
[Feature] Integrate a C7 to C8 converter plugin to the vs-code-modeler

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#121]
- [x] Description created
- [x] Reviewed by peer: @peterhnm 
- [x] Prioritised

# Description
Similar to the token-simulation plugin we want to have the possibility to convert an existing Camunda Platform 7 compatible BPMN 2.0 model to Camunda Platform 8 using [this plugin ](https://github.com/camunda-community-hub/camunda-7-to-8-migration) developed by Camunda. 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Investigate how the diagram converter plugin part could be added to the vs-code-modeler plugin 
- [ ] Add and test the converter plugin accordingly 
- [ ] Update documentation 
```

**Comment by Hafflgav** [comment]
Hey @peterhnm, 
I think this issue might be interesting for you further down the road. What do you think about this description and sub-tasks. Is it clear enough and feasible? Looking forward to your feedback.  :)
