### ISSUE TITLE
[Feature] Create a github action for miranum-cli

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#123]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
We want to introduce GitHub actions to make deployments smoother (of forms, process models and other assets to the process engine). 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Create a  Github Action for the cli api
- [ ] Test them add and them to the documentation so people are aware of how to benefit from this
```

**Comment by Hafflgav** [comment]
I am not entirely sure what we need to do here and about the current state of CI/CD topics for miranum. Once again it would be super cool if you @lmoesle could drive this forward. Thank you!

**Comment by lmoesle** [comment]
In a first approach we should implement the github action in a seperate github repository. It may be misleading for users of the action to get redirected to our monorepo.
And I don't know how well the github action integrates into our monorepo.
