### ISSUE TITLE
[Epic] Improve Miranum Console

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#124]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description         
The miranum-console is a little mess and has bad code quality that slows development down.
We should improve the miranum-console by cleaning up the code base, fixing bugs and modularise the application structure.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] #125 
- [ ] https://github.com/FlowSquad/miranum-ide/issues/145
- [ ] #127
- [ ] #126
- [ ] #128 
- [ ] https://github.com/Miragon/miranum-ide/issues/346
```

## Stakeholder
- @lmoesle 

# Acceptance
This epic is completed once all the sub-tasks are done.
