### ISSUE TITLE
[Feature] Miranum Console: Display all available files in sidebar

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#126]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
List all files in the current workspace in the sidebar.
![Image](https://user-images.githubusercontent.com/30292227/223051722-b4574faf-bd18-4c82-bb3c-5d6f1de93700.png)

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Read all files from the current workspace and display them in the sidebar
- [ ] Test Code and update documentation if applicable
```
