### ISSUE TITLE
[Refactor] Miranum Console: Improve event sourcing and application structure

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#128]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
Miranum Console uses an event sourcing approach for passing inputs between vs-code extension and webview.
We should refactor the application structure and the event sourcing (it’s not properly implemented at the moment).

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Use different commands/events for displaying a view and passing data
- [ ]  Webview: Improve React Components
- [ ]  Extension: Implement a proper cache for inputs
```
