### ISSUE TITLE
[Feature] Add deployment error handling

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#131]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [x] Prioritised

# Description
As a process engineer I want to see a detailed error description when the deployment failed. With this information I can fix problems in my process artefacts. 
Currently the error message is being hidden by the Deployment Proxy. This detail should be redirected to the user. 
When the deployment of single process artefacts fails, the whole deployment should fail to avoid inconsistencies. 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Error messages are forwarded by the deployment proxy.
- [ ] Check deployment error messages and improve them if necessary 
```

**Comment by lmoesle** [comment]
The deployment revert capabilities is a huge task. I guess we should move this task to a seperate issue

**Comment by lmoesle** [comment]
2 tickets is good for me. I just created a new ticket for the revert compatibilities https://github.com/FlowSquad/miranum-ide/issues/146.
