### ISSUE TITLE
[Feature] Provide logs in Miranum-IDE

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#132]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
As a process developer I would like to look at the logs of DigiWF to be able to analyze and fix errors when trying out my process.
Currently, process developers at LHM look at logs from DigiWF to analyze errors. We should find a way to provide process developers with the application logs without giving them direct access to Openshift/K8s.
- A possible solution could be to configure and provide Graylog, ELK Stack or something similar.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Evaluation of log solutions
- [ ] Try out a selected solution
- [ ] Create an automatic setup with Docker-compose
- [ ] Possibly deploy an additional VM with e.g. Vagrant and Ansible
```
