### ISSUE TITLE
[Feature] CLI App Authentification

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#134]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
As a process developer, I need to authenticate in order to deploy process artifacts.
- Technical authentication between proxy and DigiWF (OAuth, Spring Security).
- Demo, Prod, ... environments need token in proxy (deployment to proxy).
- In the CLI a token (OAuth) can be set via Env Variables
- 2 proxies (one for Prod and one for Test, Demo, Dev)

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] CLI reads token from Env and uses it
- [ ] Proxy forwards the token
- [ ] No authentication for local, dev
```
