### ISSUE TITLE
[Feature] Select templates without having modelled them

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#138]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
> As modeling I would like to be able to model a template directly when modeling elements to be able to use templates faster.

It should be possible to directly select a custom task (backed by an element template) instead of modelling a service task and then select the element template. e.g. If I want to model a send message task I would like to select a send message task that uses the send message element template.

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Test [extension](https://github.com/bpmn-io/bpmn-js-create-append-anything) for C7
- [ ] If changes need to be made, create a fork
```

### Acceptance criteria
- Append pattern can be used for modeling
- Camunda 7 Element Templates work (Without Icons

**Comment by lmoesle** [comment]
The repository https://github.com/bpmn-io/bpmn-js-connectors-extension is now archived. We should check if bpmn-io moved development to a different repository. If not we should maintain our own fork.

**Comment by Hafflgav** [comment]
> The repository https://github.com/bpmn-io/bpmn-js-connectors-extension is now archived. We should check if bpmn-io moved development to a different repository. If not we should maintain our own fork.

I am not aware of any other repository. I think it is valid to maintain an own fork of this repo 🤔

**Comment by peterhnm** [comment]
It is not possible to create custom tasks in C7 with this [extension](https://github.com/bpmn-io/bpmn-js-create-append-anything). The reason is the different modules used ([bpmn-js-element-templates](https://github.com/bpmn-io/bpmn-js-element-templates)).
* C8 uses [CloudElementTemplatesPropertiesProviderModule](https://github.com/bpmn-io/bpmn-js-element-templates/blob/91d3b3d7184dbb4cbe0b98ebf8f44a9ab80c6609/src/cloud-element-templates/ElementTemplatesPropertiesProvider.js). This module uses ElementTemplates with a [*createElement()*-Method](https://github.com/bpmn-io/bpmn-js-element-templates/blob/91d3b3d7184dbb4cbe0b98ebf8f44a9ab80c6609/src/cloud-element-templates/ElementTemplates.js#L32). This method is used by the Append-Extension for creating custom tasks.
* C7 uses the [ElementTemplateProviderModule](https://github.com/bpmn-io/bpmn-js-element-templates/blob/91d3b3d7184dbb4cbe0b98ebf8f44a9ab80c6609/src/element-templates/ElementTemplatesPropertiesProvider.js). Here the [*createElement()*-Method](https://github.com/bpmn-io/bpmn-js-element-templates/blob/91d3b3d7184dbb4cbe0b98ebf8f44a9ab80c6609/src/element-templates/ElementTemplates.js) is missing. Which leads to the following error: 
![Image](https://github.com/Miragon/miranum-ide/assets/100686712/450c927e-0b9b-4887-882f-9ff2f6f9283d)

@dominikhorn93 I'm not familiar with the development of bpmn-js plugins. But is it possible to extend the ElementTemplates from the ElementTemplateProviderModule with the createElement functionality? And would that be a better approach than forking the Append-Extension?
