### ISSUE TITLE
[Feature] Miranum Console: Create deployment command for the webview

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#139]
- [x] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
Update the deployment command in the web view. This needs to be tidied up by removing duplicated deployment commands . In addition react components for the deployment need to be created. 

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Remove duplicated deployment commands
    - [ ] Remove environment specific commands
    - [ ] Add 2 generic deployment commands
- [ ]  Create React component(s) for deployment.
    - [ ] Display files to be deployed in a list.
    - [ ] environments for deployment can be selected in a multiselect field
```
