### ISSUE TITLE
[Feature] Use new deployment-proxy-starter in bpm-server

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#140]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
The bpm-server uses the new Deployment Proxy Starter to deploy process artifacts
- Customize deployment endpoint in bpm-repo and invoke the DeploymentService of the Deployment Proxy Starter.
- Include and configure Deployment Proxy Starter in bpm-repo.
- Use and configure new version of bpm-repo in bpm-server (LHM)

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Customize the deployment endpoint in bpm-repo and call the DeploymentService of the Deployment Proxy Starter
- [ ] Include and configure Deployment Proxy Starter in bpm-repo
- [ ] Use and configure new version of bpm-repo in bpm-server 
- [ ] Develop concept for authentication
- [ ] Github Actions for Maven Central Release
```
