### ISSUE TITLE
[Feature] - Migrate Miranum Json Forms into miranum-ide

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#141]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
Currently, the [Miranum Json Forms Extension](https://github.com/FlowSquad/miranum-json-forms) is located in a separate repository. We want to migrate this repository to our [miranum-ide](https://github.com/FlowSquad/miranum-ide) monorepository.

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Create the apps (miranum-jsonforms and miranum-jsonforms-webview)
- [ ] Import the existing code
- [ ] Setup Vue 2 and Vue 3
- [ ] Adjust build process
```

**Comment by Hafflgav** [comment]
Lgtm @peterhnm! I moved it to ready :)

**Comment by peterhnm** [comment]
Since Nx follows a "single version policy" it is not possible to manage two versions of the same lib in one repo. Therefore it is necessary to wait until [DigiWf Form Builder and Renderer](https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-apps/packages/components) is migrated to Vue 3 to migrate Miranum Json Forms.

**Comment by lmoesle** [comment]
We already migrated miranum-json-forms into the monorepository. There's nothing further to do
