### ISSUE TITLE
[Feature] - Miranum-Deployment-Proxy: Provide a kafka deployment handler

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#170]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description

The miranum-deployment-proxy should provide a spring cloud stream deployment handler to send deployments to kafka.

**More Details**

- The deployment handler should use the already existing "kafka deployment workflow in digiwf"
- Implement a send and reply pattern: The user sends a http request to the proxy and the proxy sends a message to kafka and  waits for the answer before returning the answer to the user
- Provide configuration options and examples
- Create documentation in the [miranum-docs](https://github.com/FlowSquad)

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create Spring Cloud Stream Deployment Handler
- [ ] Create documentation for the `RestHandler` in [miranum-docs](https://github.com/FlowSquad/miranum-docs)
```
