### ISSUE TITLE
[Feature] - Refactor miranum-deployment-proxy to use feign client in the RestHandler

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#171]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description

- Refactor the `RestHandler` in miranum-deployment-proxy to use the feign client to send requests to digiwf-engine
- Create documentation for the `RestHandler` in [miranum-docs](https://github.com/FlowSquad/miranum-docs)

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Rename `RestHandler` to `DigiwfRestHandler`
- [ ] Refactor the `RestHandler` in miranum-deployment-proxy to use the feign client to send requests to digiwf-engine
- [ ] Create documentation for the `RestHandler` in [miranum-docs](https://github.com/FlowSquad/miranum-docs)
- [ ] Adjust the names of the configuration options
```
