### ISSUE TITLE
Show input and output variables in Forms Designer

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#233]
- [x] Description created
- [x] Reviewed by peer: @lmoesle 
- [ ] Prioritised

# Description
To make the live easier for the process analyst we want to be able to show input and output variables when designing forms. 
This has been added to the Camunda Forms Editor as well.  

This image shows how Camunda handles the visualisation of input and output variables. 
![image](https://github.com/Miragon/miranum-ide/assets/30292227/d8a46f81-a13f-434d-99bd-9811b7b94dd6)

## Sub-Tasks
```[tasklist]
### Tasks
- [ ] Research ways to implement this 
- [ ] Implement and test it 
- [ ] Update documentation
```
