### ISSUE TITLE
[Feature] - Add CHANGELOGs to our vscode extensions

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#242]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
To inform users of new features in our plugins we need a CHANGELOG.md for each extension.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Add CHANGELOG.md to each plugin
- [x] Update the docs on how to structure the CHANGELOG.md
```
