### ISSUE TITLE
[Feature] - Flexible file deployment

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#255]
- [ ] Description created
- [ ] Reviewed by peer: @DaAnda97 (@dominikhorn93)
- [ ] Prioritised

# Description

The miranum-deployment proxy is currently tightly coupled with the digiwf-engine. We should move the deployment logic into spring boot starters to make the deployment of process artifacts more flexible.

- The solution I came up with is to have the miranum-deployment-proxy as a single rest api for the miranum-ide to connect with. The proxy is a spring boot starter and also provided as a standalone application.
- The deployment proxy connects with a specific seployment starter which deploys the artifacts. The deployment starter provides an api (for the proxy to connect to) and calls an interface which has to be implemented by the application.
- Adapters may be enabled/disabled with configuration properties or by providing suitable dependencies

![Unbenanntes Diagramm drawio](https://github.com/Miragon/miranum-ide/assets/37705369/132e9d75-68e6-4606-b57d-f2bb27186306)

In the above picture I showed a few examples which come to mind to use the deployment-proxy and deployment starter. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create a service application for the miranum-deployment proxy
- [ ] Create a spring boot starter structure for the deployment starter project (Parts of this are already implemented in #170 )
- [ ] Implement deployment starter logic (API Interface, Deployment Interface)
- [ ] Implement Adapters for local use case
- [ ] Implement Adapters for rest use case
- [ ] Enable/disable adapters with configuration properties or by providing suitable dependencies
```

**Comment by lmoesle** [comment]
Parameter Namespace (kann der Projektname sein), Parameter Tags (neues statt Version)

```
boolean deploy(file, type, namespace, tag)
```
