### ISSUE TITLE
[Feature] - Improve UX/UI of Miranum Console

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#346]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [x] Prioritised

# Description
The Miranum Console UI is very minimalistic for now. We want to integrate the extension more into VS Code. The following wireframes are first ideas of how we want to achieve this. Also, we will be using Vue instead of React, since we already use Vue for our form builder.

Miranum Console             |  Welcoming Page
:------------------------:|:-------------------------:
![grafik](https://github.com/Miragon/miranum-ide/assets/100686712/90be9b94-402b-4e57-8d07-b211c22d3b4c) |  ![grafik](https://github.com/Miragon/miranum-ide/assets/100686712/77b8735a-53d4-485d-816c-451c63b63d6d)

New Project                      |  New File
:------------------------:|:-------------------------:
![grafik](https://github.com/Miragon/miranum-ide/assets/100686712/e718ca07-cf3b-4340-a6e0-0ef1c3549956) |  ![grafik](https://github.com/Miragon/miranum-ide/assets/100686712/a60b9af7-3f82-4741-b5e2-68211ae8d306)

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Setup Vue
- [ ] Create `Welcoming Page`
- [ ] Create `New Project` Popup Window
- [ ] Create `Command` TreeDataProvider
- [ ] Create `Artefacts` TreeDataProvider
- [ ] Improve the `Project View`
```

**Comment by Hafflgav** [comment]
Cool idea @peterhnm! It looks pretty good to me 💯
