### ISSUE TITLE
[Feature] - Secure artifact deployments with authentication

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#371]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description

Implement authentication in the miranum-ide (miranum-cli and miranum-deployment).

We have 3 different scenarios for authentication:
- **Miranum-cli**: On the miranum-cli the user has to login in before deploying files to miranum-deployment. The user has to login once (not for every deployment).
- **Miranum-console**: Implement a similar authentication to miranum-cli in the vscode plugin
- **Github Actions**: Authentication should happen with api keys or credentials saved in the github secrets manager. Therefore we should allow setting auth credentials through env variables

The miranum-deployment-service should also implement authentication and use an oauth service account to call the deployment receivers

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Create a concept on how authentication can be done for cli application and vscode plugins
- [ ] Implement authentication for miranum-cli
- [ ] Implement authentication for miranum-deployment
- [ ] Implement authentication for miranum-console
- [ ] [Enable authentication for deployment endpoints in miranum-platform](https://github.com/Miragon/miranum-platform/issues/27)
```
