### ISSUE TITLE
[Feature] Create first version of the plugin

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#411]
- [x] Description created
- [x] Reviewed by peer:
- [x] Prioritized

# Description
Create the necessary applications under apps/ for the new **Miranum Config Editor Plugin**.

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Create node application
- [x] Create vue 2 application
- [x] Install dependencies
- [x] Create the frontend/webview
- [x] Create the backend
- [x] Write the documentation
```
