### ISSUE TITLE
[Epic] - Support Monorepo structures for process modelling

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#466]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description

**As a citizen developer I would like to create multiple processes in a single git repository.**

I would like to create multiple processes with subprocesses in a single repository. I would like to store multiple forms and element-templates in a subdirectory of *forms* / *element-templates* and deploy all artifacts with a single command. I also would like to manage everything with a single miranum.json file.

The deployment of files already works as expected but the generation of files and the modeller don't work as expected.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] #451 
- [ ] The generation of new bpmn and dmn files appear always in the root directory eventhough another directory is specified in the miranum.json
- [ ] Drag and Drop in the miranum-console file view does not work
```

## Stakeholder
 

# Acceptance
 

- [ ] Projectstructures like in the [monorepo-example](https://github.com/Miragon/miranum-ide/tree/feature/monorepo-modelling-support/resources/monorepo-example) shown are supported
