### ISSUE TITLE
[Epic] - Switch from DigiWf Forms to JSON Forms

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#523]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description
We will no longer maintain the Plugin for DigiWf Forms.
Instead, the [JSON Forms Plugin](https://github.com/Miragon/miranum-json-forms/) should be added to the monorepo.
Since this plugin uses Vue 3, the dependency on Vue 2 has to be removed and replaced by Vue 3.
This affects the Miranum Config Editor which uses Vue 2 + Vuetify.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Remove the `DigiWf Form` Plugin
- [ ] https://github.com/Miragon/miranum-ide/issues/524
- [x] Add the `JSON Forms` Plugin
```

**Comment by peterhnm** [comment]
After adding the new dependencies and applications `nx` command fail with `TypeError: Failed to process project dependencies with "@nxrocks/nx-spring-boot".`

An issue to this topic can be found [here](https://github.com/tinesoft/nxrocks/issues/217).
