### ISSUE TITLE
[Feature] - Deprecate obsolete plugins

### ISSUE THREAD

**Issue by peterhnm** [Miragon/miranum-ide#718]
# Description

We have several plugins that are not developed regularly and are not used much. This issue is to discuss which plugins should be removed and marked as obsolete.

## Sub-Tasks

 

```[tasklist]
### Tasks
- [x] <your-issue-here>
- [x] Unpublish extension ([here](https://marketplace.visualstudio.com/manage/publishers/miragon-gmbh))
- [ ] Remove extension from repository
```
